version: "3.8"

services:
  frontend:
    image: bum1215k/maple-nginx
    container_name: nginx-proxy
    ports:
      - "80:80"

  backend:
    image: bum1215k/mapleproject:latest
    container_name: backend-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI
      - FIREBASE_PROJECT_ID
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_PRIVATE_KEY
