// backend/models/Inventory.js
import mongoose from "mongoose";

const inventorySchema = new mongoose.Schema({
  userId: { type: String, required: true },
  uuid: { type: String, required: true },
  item_equipment_part: String,
  item_equipment_slot: String,
  item_name: String,
  item_icon: String,
  item_description: String,
  item_shape_name: String,
  item_shape_icon: String,
  item_gender: String,
  item_total_option: Object,
  item_base_option: Object,
  potential_option_grade: String,
  additional_potential_option_grade: String,
  potential_option_flag: String,
  potential_option_1: String,
  potential_option_2: String,
  potential_option_3: String,
  additional_potential_option_flag: String,
  additional_potential_option_1: String,
  additional_potential_option_2: String,
  additional_potential_option_3: String,
  equipment_level_increase: Number,
  item_exceptional_option: Object,
  item_add_option: Object,
  growth_exp: Number,
  growth_level: Number,
  scroll_upgrade: String,
  cuttable_count: String,
  golden_hammer_flag: String,
  scroll_resilience_count: String,
  scroll_upgradeable_count: String,
  soul_name: String,
  soul_option: String,
  item_etc_option: Object,
  starforce: String,
  starforce_scroll_flag: String,
  item_starforce_option: Object,
  special_ring_level: Number,
  date_expire: String,
  price: Number,
});

const Inventory = mongoose.model("Inventory", inventorySchema);
export default Inventory;
