name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy on EC2
      run: |
        mkdir -p ~/MapleProject
        cd ~/MapleProject

        curl -sSf -o docker-compose.yml https://raw.githubusercontent.com/bum7382/MapleProject/main/docker-compose.yml

        export MONGODB_URI="${{ secrets.MONGODB_URI }}"
        export FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}"
        export FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}"
        export FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}"

        docker-compose down -v
        docker-compose pull
        docker-compose up -d
