name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest image (backend + nginx)
      run: |
        cd /home/ubuntu/MapleProject
        docker-compose pull

    - name: Restart all services
      run: |
        cd /home/ubuntu/MapleProject
        docker-compose down -v
        docker-compose up -d --build
